# Generated by Django 3.0.6 on 2020-05-24 05:59

from django.db import migrations

from django_taskflow.base_operations import forward, backward
from django_taskflow.example_data import add_examples, remove_examples


class Migration(migrations.Migration):

    dependencies = [
        ('django_taskflow', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
        migrations.RunPython(add_examples, remove_examples),
    ]
